name: release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build_fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Build
        working-directory: frontend
        run: |
          npm i && npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: fe_dist
          path: frontend/build
          retention-days: 1
  build_be:
    needs: build_fe
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the dist of FE
        uses: actions/download-artifact@v4
        with:
          name: fe_dist
          path: frontend/build/
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Prepare for Linux and Windows
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64
      - name: Build for Linux and Windows
        run: |
          go build -o ./build/fusion ./cmd/server/server.go
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: "be_${{ matrix.os }}_dist"
          path: |
            build/fusion
          retention-days: 1
